### ISSUE TITLE
Missing Pal subspecies

### ISSUE THREAD

**Issue by erikalira** [mlg404/palworld-paldex-api#1]
Hello! 

the api does not have Pal Subspecies yet

![image](https://github.com/mlg404/palworld-paldex-api/assets/35104052/c6a502b9-a56a-415b-ad0a-ac38e73445f9)

source: [https://palworld.fandom.com/wiki/Paldeck](https://palworld.fandom.com/wiki/Paldeck)

**Comment by mlg404** [comment]
currently working on that! Thanks for open this issue!!!

**Comment by mlg404** [comment]
Subspecies added! Thx!
