### ISSUE TITLE
Medicine production suitability

### ISSUE THREAD

**Issue by c-eric** [mlg404/palworld-paldex-api#11]
Hey, I noticed this issue for the medicine production suitability:
![image](https://github.com/mlg404/palworld-paldex-api/assets/43305167/24203e27-3cb0-4435-8ce3-7d37b07723dc)

**Comment by mlg404** [comment]
Holy..... thx. I will fix that

**Comment by mlg404** [comment]
Fixed! Thank you very much for this issue
