### ISSUE TITLE
add pal's location

### ISSUE THREAD

**Issue by mlg404** [mlg404/palworld-paldex-api#17]
the wiki now support natural habitat
https://palworld.fandom.com/wiki/Lamball
example:
![Captura de tela de 2024-01-30 13-28-04](https://github.com/mlg404/palworld-paldex-api/assets/5060732/111ba61d-6d58-4ccc-845d-b357d9fb6e1a)

we should implement this

**Comment by mlg404** [comment]
@Xyrrm feature implements a json from custom maps
I'm thinking in a way to implements his json with current API, so i will let this Issue open for now

thx for effort @Xyrrm

**Comment by Xyrrm** [comment]
The location data and map is pulled directly from the games files. Ill try to do some math later to line up coordinates correctly.
