### ISSUE TITLE
LICENSE file missing in the repo

### ISSUE THREAD

**Issue by luigiMinardi** [mlg404/palworld-paldex-api#2]
Hey, very interesting project that you're developing! 

I saw that you disclosed on the [readme](https://github.com/mlg404/palworld-paldex-api/blob/main/README.md?plain=1#L153) that the project is under the MIT license but you don't have the license on the repo and the readme link is also broken (because the file does not exist).

Can you please provide the LICENSE of the project on the repo?

Thanks!

**Comment by mlg404** [comment]
Thanks! Solved!
