### ISSUE TITLE
[question] does this api have breeding info too?

### ISSUE THREAD

**Issue by Poojan-20** [mlg404/palworld-paldex-api#33]
Implementing an api which also provides information about which pal breed with another would produce which pals with good or best stats and better passive skills ( also taking into consideration a passive skill as an factor).

Just an thought let me know what do yall think about it ?

**Comment by mlg404** [comment]
I think it's awesome!

**Comment by augustoerico** [comment]
That would be nice, indeed. What structure do you have in mind? I was thinking something along the lines:
```json
    ...,
    "breeding": {
        "parent1": { ... },
        "parent2": { ... }
    }
```

Let me know what you guys think

**Comment by LoopingStudio** [comment]
I think with an Array it would be better, because there is more than 1 combinaison:
`
    ...,
    "breeding": [
        {
            "parent1": "010",
            "parent2": "45B"
        },
        {
            "parent1": "030",
            "parent2": "110"
        }
    ]
`

What do you think its better ?

**Comment by mlg404** [comment]
> I think with an Array it would be better, because there is more than 1 combinaison:
> 
> ```
> 
>     ...,
> 
>     "breeding": [
> 
>         {
> 
>             "parent1": "010",
> 
>             "parent2": "45B"
> 
>         },
> 
>         {
> 
>             "parent1": "030",
> 
>             "parent2": "110"
> 
>         }
> 
>     ]
> 
> ```
> 
> 
> 
> What do you think its better ?

Instead a json on parents combination, we can do other array, to be simple, like:

```
...,
"breeding": [
    ["010", "45B"],
    ["030", "110"],
]
```

What do you think?

**Comment by Poojan-20** [comment]
I have very less knowledge about how to write api's like this but i could easily integrate them into an app (or i might learn how to write api). As per my learning using an array for parents would help saving space and potentially making the data file smaller

This seems like an great addition to the paldex api, since it would make it easier for other devs to build around palworld breed apps. 
even i wanted to build one breed calculator(with ofcourse a passive skill) to make it seamless for users.

You can refer this doc to gain knowledge about how breeding works [Breedingdocs](https://docs.google.com/spreadsheets/u/1/d/1YgPc11dgdBUC8jXNp01b7gI6jNHoBRQGwrY_V6lXMgQ/htmlview?usp=sharing)

**Comment by augustoerico** [comment]
Yeah, you're right, `breading` would have to be an array. I still would suggest each item to be an object, because in future iterations we might wanna add some more properties to said objects without causing a breaking change. I was thinking more specifically in terms of HATEOAS on API evolution.

**Comment by yoonhok524** [comment]
Changes regarding this item have been submitted as a PR. Please check the link below for confirmation.
https://github.com/mlg404/palworld-paldex-api/pull/35

**Comment by mlg404** [comment]
I will close this issue bc last merge
