### ISSUE TITLE
[Question] Support Android / iOS applications for the API

### ISSUE THREAD

**Issue by viethua99** [mlg404/palworld-paldex-api#34]
I'm developing a mobile project (Android / iOS) based on your API, and it works great. I would appreciate it if you gave me a review and attached my project to your README file so that everybody can use it.

Here is the link for my project: https://github.com/viethua99/Paldex

iOS:

![Simulator Screen Shot - iPhone 14 Pro - 2024-02-07 at 17 39 06](https://github.com/mlg404/palworld-paldex-api/assets/39612597/47f16e04-7ebc-4640-82b3-727511f7c7ef)

Android:

![Screenshot_1707302200](https://github.com/mlg404/palworld-paldex-api/assets/39612597/036a9556-fd64-467f-97d5-87a9f3fe43a3)

**Comment by LoopingStudio** [comment]
Hey ! Do you plan to publish it ? I'm making an app for Apple Vision Pro as well

**Comment by viethua99** [comment]
Not really, I just started working on this project using local host. The API has not published yet

**Comment by mlg404** [comment]
Super cool. I'm not at home until sunday. When i do I will add it to our readme!

**Comment by viethua99** [comment]
Thank you so much!!

**Comment by mlg404** [comment]
Added! Thx! Beautiful app btw!
