### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by stolenvw** [mlg404/palworld-paldex-api#49]
### What platform is your computer?

Linux 5.15.0-91-generic x86_64 x86_64

### What steps can reproduce the bug?

git clone repo and run with docker-compose

### What do you see instead?

```
$ bun --watch run ./src/index.ts
error: Cannot find module "@services/index" from "/usr/src/app/src/useCases/pals/list/list-pals.usecase.ts"
```

**Comment by mlg404** [comment]
thx! I will fix that
