### ISSUE TITLE
Add a key to item.json

### ISSUE THREAD

**Issue by yoonhok524** [mlg404/palworld-paldex-api#52]
### What is the problem this feature would solve?

The drop item information in pals.json consists of lowercase letters without spaces. 
There's no matching information in item.json except for the name. 

### What is the feature you are proposing to solve the problem?

How about adding the key value to item.json? 
If that's acceptable, may I submit a PR after adding it?

**Comment by mlg404** [comment]
It seems nice! You can take that!

**Comment by mlg404** [comment]
Closing this bc of #53
