### ISSUE TITLE
Work suitability types are inconsistent

### ISSUE THREAD

**Issue by ludvigtj** [mlg404/palworld-paldex-api#6]
There are some inconsistencies specifically in the casing of names of work suitability. Below are my findings:
id 37 and 117 has a suitability element with type: "Lumbering", while any other occurrence is fully lowercase "lumbering". 
The suitabilities that are composed of two words have uppercase of the first letters of each word. 
One word suitabilities are fully lowercase (except the above lumbering one)

This occured on 27/01/2024, as response to a get request, with parameter ?limit=137
[paldeck.json](https://github.com/mlg404/palworld-paldex-api/files/14072315/paldeck.json)

**Comment by ludvigtj** [comment]
It seems that in the case of the uppercase "Lumbering ", there is a trailing space aswell

**Comment by mlg404** [comment]
thx for this! I will fix that!

**Comment by mm64z** [comment]
there's also a suitability with a null level value, Suzaku Aqua
Looks like it should be 3

**Comment by mlg404** [comment]
Everything now is lower case and snaked case
