### ISSUE TITLE
Which auras require crafted item

### ISSUE THREAD

**Issue by mm64z** [mlg404/palworld-paldex-api#8]
Hello, appreciate the work!
I was wondering if you planned to add something that indicated if an aura needed a crafted item to be enabled.
I was thinking maybe an additional field underneath aura

**Comment by mlg404** [comment]
It sounds like a good idea

**Comment by yoonhok524** [comment]
@mlg404 
Do you have any plans to add a Craft item list?

**Comment by mlg404** [comment]
> @mlg404 
> 
> Do you have any plans to add a Craft item list?

Yes! I just need some time to do that!

**Comment by mlg404** [comment]
> Hello, appreciate the work! I was wondering if you planned to add something that indicated if an aura needed a crafted item to be enabled. I was thinking maybe an additional field underneath aura

I just added support for this, but my info source has only the FoxParks tech (Tech Needed)
I get info (automatic) from this wiki https://palworld.fandom.com/wiki/Foxparks
When all Pal's get theirs respectives techs, i update this issue branch with fresh data
![Captura de tela de 2024-01-29 23-54-04](https://github.com/mlg404/palworld-paldex-api/assets/5060732/cd077fdc-ee9e-4217-a1e0-75f84c34e779)

**Comment by mlg404** [comment]
nevermind
i just added all info to the wiki by myself and scraped it all too

**Comment by mlg404** [comment]
PR #12 
BRANCH #16 

Just merged it to main.
i closed the wrong issue so i'm commenting this
